// House-style copy check: no em-dashes (—) or en-dashes (–) anywhere in the public copy or the
// shipped source. The em-dash is the classic "written by a machine" tell; this project's voice
// uses plain punctuation (commas, periods, colons, parentheses) instead, the same as the
// Übermensch landing page. Run in CI / before release.
//
//   node scripts/copy-check.mjs   # exit 0 if clean, exit 1 (with locations) if any dash found
//
// src/wasm/ is excluded: it is generated by wasm-pack and its doc comments are not our copy.

import { readFileSync, readdirSync, statSync } from "node:fs";
import { join, extname } from "node:path";

const BANNED = [
  { ch: "—", name: "em-dash (—)" },
  { ch: "–", name: "en-dash (–)" },
];
const SCAN_EXT = new Set([".ts", ".css", ".html", ".md", ".mjs"]);
const SKIP_DIRS = new Set(["node_modules", "dist", "src/wasm", ".git", "test-results", "screenshots"]);

const roots = ["README.md", "index.html", "src", "scripts", "tests"];
const files = [];
function walk(p) {
  const rel = p.replace(/^\.\//, "");
  if (SKIP_DIRS.has(rel)) return;
  const st = statSync(p);
  if (st.isDirectory()) {
    for (const e of readdirSync(p)) walk(join(p, e));
  } else if (SCAN_EXT.has(extname(p))) {
    files.push(p);
  }
}
for (const r of roots) {
  try {
    walk(r);
  } catch {
    /* missing path is fine */
  }
}

const hits = [];
for (const f of files) {
  // copy-check.mjs itself names the banned characters on purpose; don't flag it.
  if (f.endsWith("copy-check.mjs")) continue;
  const lines = readFileSync(f, "utf8").split("\n");
  lines.forEach((line, i) => {
    for (const b of BANNED) {
      if (line.includes(b.ch)) {
        hits.push(`${f}:${i + 1}  ${b.name}  →  ${line.trim().slice(0, 90)}`);
      }
    }
  });
}

if (hits.length) {
  console.error(`COPY CHECK FAILED — ${hits.length} banned dash(es) found:\n`);
  for (const h of hits) console.error("  " + h);
  console.error("\nReplace em/en dashes with plain punctuation (comma, period, colon, parentheses).");
  process.exit(1);
}
console.log(`COPY CHECK CLEAN — scanned ${files.length} files, no em/en dashes.`);
